# Generated by Django 5.2.7 on 2025-10-29 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='status',
            field=models.CharField(choices=[('GENERATED', 'Generated'), ('APPROVED', 'Approved by User (Ready to Book)'), ('CANCELLED', 'Cancelled')], default='GENERATED', help_text='The current status of the itinerary in the approval lifecycle.', max_length=20),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
